routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use Illuminate\Http\Request;

/*Route::group(['middleware' => ['role:user']], function () {


});*/
Route::get('test-notification', 'HomeController@sendToken');
Route::post('/', 'HomeController@storeToken')->name('send');
Route::post('forget-password','auth\ForgotPasswordController@submitForgetPasswordForm')->name('forget.password.post'); 
Route::get('passwords/reset', 'auth\ForgotPasswordController@showForgetPasswordForm')->name('forget.password.get');
Route::get('reset-password/{token}', 'auth\ForgotPasswordController@showResetPasswordForm')->name('reset.password.get');
Route::post('reset-password', 'auth\ForgotPasswordController@submitResetPasswordForm')->name('reset.password.post');
Route::get('/mark-as-read', 'auth\ForgotPasswordController@markAsRead')->name('mark-as-read');

        Auth::routes();

        Route::post('sitecodename', 'SiteController@siteCodeName')->name('sitecodename');
        Route::post('lo', [App\Http\Controllers\loController::class, 'logout'])->name('lo');

       

        Route::group(['middleware' => ['auth']], function() {
            Route::get('solars/{solar}/e', 'SolarController@editnumber');
            Route::post('solar/s', 'SolarController@updatenumber');
        
        Route::resource('sites', 'siteController');
        Route::get('/siteimport', 'sitecontroller@import_excel')->name('siteimport');  
        Route::get('powersolution', 'siteController@solution')->name('solution');
        Route::resource('generators', 'GeneratorController');
        Route::get('generator/warehouse', 'GeneratorController@warehouse')->name('generatorswarehouse');
        Route::get('generators/add/action', 'GeneratorController@addaction')->name('addaction');
        Route::resource('tanks', 'TankController');
        
        Route::resource('solars', 'SolarController');  
        Route::get('solar/warehouse', 'SolarController@warehouse')->name('solarswarehouse');
        Route::get('tanks/newcreate/{generator}', 'TankController@creategeneratortank')->name('newtankcreate');
        Route::post('tanks/newcreate/{generator}', 'TankController@storegeneratortank')->name('newtankscreate');
        Route::get('tanksimport', 'TankController@import_excel')->name('tanksimport');
        Route::post('import-tank', 'TankController@import');
        Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
        Route::get('/poweractions', [App\Http\Controllers\HomeController::class, 'poweractions'])->name('poweractions');
       
        Route::get('warehousesolution', 'warehouseController@solution')->name('warehoussolution');

  
        Route::resource('warehouses', 'WarehouseController');
       
        Route::get('battery/warehouse', 'BatteryController@warehose')->name('batterywarehouse');
       
        Route::post('cheack_warehouse', 'WarehouseController@cheackWarehouse')->name('cheack_warehouse');



        Route::get('cabinet/warehouse', 'CabinetController@warehouse')->name('cabinetwarehouse');
        Route::get('cabinet/shipment/create', 'CabinetController@craeteShipment')->name('ch');
       Route::post('cabinet/shipments/create', 'CabinetController@addShipment')->name('csh');

       Route::resource('batteries', 'BatteryController');

       Route::get('battery/shipment/create', 'BatteryController@craeteShipment');
       Route::post('battery/shipment', 'BatteryController@addShipment')->name('batteryshipment');
       Route::resource('cabinets', 'CabinetController');
        Route::group(['middleware' =>['role:Management']], function () {

        Route::resource('roles', 'RoleController');
        Route::resource('users', 'UserController');
        Route::get('site/track', 'AuditsController@track');
        Route::get('cabinet/track', 'AuditsController@cabinetTrack')->name('cabinet_track');
        Route::get('generator/track', 'AuditsController@index')->name('track');
        Route::get('generator/track/{generator}', 'AuditsController@trackshow')->name('generatortrack');
      
        Route::get('tank/track', 'AuditsController@tankTrack')->name('tank_track');
        Route::get('solar/track', 'AuditsController@solarTrack')->name('solar_track');

        Route::post('site/destroy/{id}',  'SiteController@des')->name('des');
        Route::get('siteexport','sitecontroller@export');
        Route::get('battery/track', 'AuditsController@batterytrack')->name('battery-track');

                                                                 });

    


    
     
        Route::resource('amperes', 'AmpereController');
      
     

        Route::get('import-file', 'HomeController@import')->name('import-file');
        Route::get('batteryimport', 'BatteryController@import_ex')->name('batteryimport');
        Route::post('import-battery', 'BatteryController@importExcelCSV');
        Route::get('generatorimport', 'GeneratorController@import_ex')->name('generatorimport');
        Route::post('import-excel-csv-file', 'GeneratorController@importExcelCSV');
        Route::get('ampereimport', 'AmpereController@import_ex')->name('ampereimport');
        Route::post('import-ampere', 'AmpereController@importExcelCSV');
       

        Route::get('solarimport', 'SolarController@import_excel')->name('solarimport');
        Route::post('import-solar', 'SolarController@import');
        Route::get('cabinet_import', 'CabinetController@import_excel')->name('cabinetimport');
        Route::post('import-cabinet', 'CabinetController@import');
       
        Route::post('import', 'sitecontroller@import');  



    Route::get('genes/{generator}/e', 'GeneratorController@editnumber');
 
    Route::post('generator/s', 'GeneratorController@updatenumber');

   
    Route::get('batts/{battery}/e', 'BatteryController@editnumber');
    Route::post('battery/s', 'BatteryController@updatenumber');
    Route::get('battery/shipment/create', 'BatteryController@craeteShipment')->name('batteryshipmentcreate');
 
    Route::get('in', 'GeneratorController@in');

   

    Route::post('tabledit/action', 'GeneratorController@action')->name('tabledit.action');
    Route::get('searchform', [App\Http\Controllers\GeneratorController::class,'compare'])->name('searchform');
   /* Route::get('searchform', 'GeneratorController@form');*/

    Route::get('searchs', 'GeneratorController@search')->name('searchs');

    Route::get('cabinet/dismantle', 'GeneratorpoweractionController@cabinetDismantle');
    Route::get('cabinet/reshuffling', 'GeneratorpoweractionController@cabinetReshuffling');
    Route::get('cabinet/install', 'GeneratorpoweractionController@cabinetInstall');



    Route::get('sitesearch', [App\Http\Controllers\siteController::class,'search'])->name('sitesearch');
    
 
    Route::get('reshuffling', 'GeneratorpoweractionController@reshuffling')->name('re');
    Route::get('dismantle', 'GeneratorpoweractionController@dismantle')->name('dismantle');
    Route::get('battery/dismantle', 'GeneratorpoweractionController@batteryDismantle')->name('bdismantle');
    Route::get('battery/reshuffling', 'GeneratorpoweractionController@batteryReshuffling')->name('bre');
    Route::get('install', 'GeneratorpoweractionController@install')->name('install');
    Route::get('battery/install', 'BatteryController@install')->name('batteryinstall');
    Route::get('solar/install', 'SolarController@install')->name('solarinstall');
    Route::get('poweractions/create/', 'GeneratorpoweractionController@create')->name('powercreate');
    Route::put('/poweractions/create', 'GeneratorpoweractionController@store')->name('powerscreate');
    Route::put('/poweractions/create/rep', 'GeneratorpoweractionController@storee')->name('powerscreaterep');
  //  Route::put('/poweractions/reinstall', 'GeneratorpoweractionController@reinstall')->name('reinstall');
    Route::put('/poweractions/create/battery', 'GeneratorpoweractionController@batterystore')->name('powerscreatebattery');
   
    Route::get('generator/shipment/create', 'GeneratorController@craeteShipment')->name('shipmentcreate');
    Route::get('solar/shipment/create', 'SolarController@craeteShipment')->name('solarshipmentcreate');
    Route::post('solar/shipment', 'solarController@addShipment')->name('solarshipment');
    Route::post('generator/shipment', 'GeneratorController@addShipment')->name('shipment');
  

    Route::get('poweraction', [App\Http\Controllers\GeneratorController::class,'powerAction'])->name('poweraction');
  
   
    Route::resource('gene', 'AuditsController');
 
    Route::get('ampere/track', 'AuditsController@amperetrack');
   
    Route::get('/users/{id}/password', 'UserController@password')->name('editpassword');
    Route::post('/users/{id}/password', 'UserController@changePassword')->name('userpassword');

    Route::get('cabinetactions', 'CabinetController@actions')->name('cabinetactions');
    Route::get('bactions', 'BatteryController@actions')->name('bactions');
    Route::get('solar/actions', 'SolarController@addaction')->name('solaractions');



    Route::delete('tanks/{tank}','TankController@destroy')->name('tankdes');
  

 

    
 



});


Route::get('/p', [App\Http\Controllers\siteController::class, 'test']);



 Route::get('oi', 'sitecontroller@exportt');
 Route::post('oi', 'sitecontroller@exportt');
 Route::get('generator/export/',  'GeneratorController@export')->name('geneexport');

 Route::get('cabinets/{cabinet}/e', 'CabinetController@editnumber');
 Route::post('cabinets/s', 'CabinetController@updatenumber');

 Route::get('dismantle/{generator}/e', 'generatorController@editdismantle');
 Route::post('dismantle/s', 'generatorController@updatedismantle');
 
 Route::get('reshuffling/{generator}/e', 'generatorController@editreshuffling');
 Route::post('reshuffling/s', 'generatorController@updatereshuffling');
 Route::get('cabinetreshuffling/{cabinet}/e', 'cabinetController@editreshuffling');
 Route::post('cabinetreshuffling/s', 'cabinetController@updatereshuffling');

app/Models/Cabinet.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use App\Models\Battery;
use App\Models\Warehouse;
use OwenIt\Auditing\Auditable;
use OwenIt\Auditing\Contracts\Auditable as AuditableContract;
use App\Models\Audit;
class Cabinet extends Model implements AuditableContract
{
    use HasFactory;


    use Auditable;

    protected $fillable =['cabinet_name','number','is_used','oracle_code','installation_date','is_active','shipment_date','dismantle_date'];

    public function site()
    {
        return $this->belongsTo(Site::class);
    }

    public function warehouse()
    {
        return $this->belongsTo(Warehouse::class);
    }
        public function sitecabinet()  
        {
            return $this->hasMany(Sitecabinets::class, 'cabinet_id', 'id');
        }
 public function battery()  
        {
            return $this->hasMany(Battery::class, 'cabinet_id', 'id');
        }

        public function generatorpoweraction( )  
        {
            return $this->hasMany(Generatorpoweraction::class);
        }
    
      
    }

resources/views/cabinets/create.blade.php
@extends('layouts.app')
@section('content')
@if ($message=Session::get('success'))


<div class="container">
    <div class="alert alert-primary" role="alert">
        {{$message}}
    </div>
</div>
@endif
@if ($errors->any())

<div class="alert alert-danger">
   <ul>
       @foreach ($errors->all() as $error)
           <li>

            {{ $error }}</li>
       @endforeach
   </ul>
</div>
@endif

<form action="{{route('cabinets.store')}}" method="POST">
    @csrf
    <div class="raw">
    <div class="column">

    <div class="form-group">
                <strong>Site code:</strong>
                <input type="text" name="site_code" class="form-control" placeholder="Site code" id="site_code" required>
                <span id="error-message" style="color: red; display: none;">* the site is not available *</span>
            </div>
<div class="form-group">
            <strong>Cabinet type:</strong>
            <input type="text" name="cabinet_name" class="form-control" placeholder="Cabinet Name" required>

        </div>
    


            <strong>Status</strong> <br> 
        <select name="is_used"  class="form-control" required>
        <option value="">Select status</option>  
  <option value="used">Used</option>
  <option value="new">New</option>

</select>
            </div>
            
            <div class="column">
            <div class="form-group">
            <strong>Oracle Code  :</strong>
            <input type="text" name="oracle_code" class="form-control" placeholder="Oracle code" required>

        </div>
        <div class="form-group">
                <strong>Installation date:</strong>
                <input type="date" name="installation_date" class="form-control"  required>

            </div>
            <div class="form-group">
                <strong>PR:</strong>
                <input type="number" name="pr" class="form-control"  required>

            </div>

</div>
<div class="pull-right">
    <button class="button">create</button>
   </div>
</div>




<script>

        $(document).ready(function(){

                $("#site_code").on('change', function(){
        var siteCode = $(this).val();

$.ajax({
        url: "{{ route('cheack_site') }}",
            method: 'POST',
            data: {
                _token: "{{ csrf_token() }}",
                site_code: siteCode
            },
            dataType:'json',
         
            success: function(response) {
           if(response.b){
            
           }
              if(response.a){
                $('#error-message').hide();
              }
              else{
                $('#error-message').show();
      
            document.getElementById("site_code").value="";

              }
            
    },
});

});
        });
</script>
      
   

   

     

@endsection

resources/views/cabinets/createwarehouse.blade.php
@extends('layouts.app')
@section('content')

@if ($errors->any())

<div class="alert alert-danger">
   <ul>
       @foreach ($errors->all() as $error)
           <li>

            {{ $error }}</li>
       @endforeach
   </ul>
</div>
@endif







<form action="{{route('csh')}}" method="POST" id="myForm">
    @csrf
    <div class="raw">
<div class="column">




            <div class="form-group">
                <strong>Warehouse name:</strong>
                <input type="text" name="warehouse_name"  id="warehouse_name"class="form-control" placeholder="Warehouse" required>
                <span id="error-message" style="color: red; display: none;">* the warehouse is not available *</span>
            </div>
            

            


            <div class="form-group">
        <strong>Numbers:</strong>
        <input type="text" name="number" class="form-control" placeholder="number" required>

    </div>

  
    <div class="form-group">
        <strong>Shipment date:</strong>
        <input type="date" name="shipment_date" class="form-control" placeholder="Shipment date" required>

    </div>
</div>
<div class="column">

<div class="form-group">
        <strong>Status:</strong>
        <select class="form-control" name="is_used"   placeholder="Is uesed!" required >
            <option value="">Select status</option>

        <option value="used">Uesed</option>
        <option value="new" >New</option>
  
    </select>

</div>



<div class="form-group">
    <strong>Oracle code :</strong>
    <input type="number" name="oracle_code" class="form-control" placeholder="Oracle code" required>

</div>



<div class="form-group">
    <strong>Cabinet name :</strong>
    <input type="text" name="cabinet_name" class="form-control" placeholder="Cabinet name" required>

</div>

</div>





<div class="pull-right">

    <button class="button" type="submit" >Add</button>
   </div>
    </div>

</div>


</form>
</div>
</div>

<script>
    $("#warehouse_name").on('change',function(){

 var warehouseName= $(this).val();
 console.log(warehouseName);
 $.ajax({
    url: "{{ route('cheack_warehouse') }}",
    method: 'POST',
            data: {
                _token: "{{ csrf_token() }}",
                warehouse_name:warehouseName
            },
            dataType:'json',
         
            success: function(response) {
        
              if(response.a){
               
                $('#error-message').hide();
              
              }
              if(response.b){
        
                $('#error-message').show();
      
            document.getElementById("warehouse_name").value="";

              }
            
    },
 });

    });
</script>
@endsection

resources/views/cabinets/dismantle.blade.php
@extends('layouts.app')
@section('content')

@if ($message=Session::get('success'))


<div class="container">
    <div class="alert alert-primary" role="alert">
        {{$message}}
    </div>
</div>
@endif

<div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <h4>
                            <div class="pull-right">
                         

</div>
                        </h4>
               
                        <h6>
                
            
                        </h6>
                  
                       
                    </div>
                    <div class="card-body">

                        <table class="table table-bordered table-striped" id="example">
                            <thead>
                                <tr>


            <th style="text-align:center" class="formTableTitle" style="text-align:center" nowrap ><span class="tableheadtext" >Cabinet id</span> </th>
  
            <th style="text-align:center" class="formTableTitle" style="text-align:center" nowrap ><span class="tableheadtext" >Cabinet type</span> </th>
            <th style="text-align:center" class="formTableTitle" style="text-align:center" nowrap ><span class="tableheadtext" >Action name</span> </th>
            <th style="text-align:center" class="formTableTitle" style="text-align:center" nowrap ><span class="tableheadtext" >Form site</span> </th>
            <th style="text-align:center" class="formTableTitle" style="text-align:center" nowrap ><span class="tableheadtext" >Action time</span> </th>

            <th style="text-align:center" class="formTableTitle" style="text-align:center" nowrap ><span class="tableheadtext" >Craeted by mame</span> </th>


            <th style="text-align:center" class="formTableTitle" style="text-align:center" nowrap ><span class="tableheadtext" >RM</span> </th>
            

         </tr>
        <tbody>
            @foreach ($dismantles as $dismantle)
          
          
            <tr>
            <td style="text-align:center">{{$dismantle->cabinet->id}}</td>
            <td style="text-align:center">{{$dismantle->cabinet->cabinet_name}}</td>

            <td style="text-align:center">{{$dismantle->poweraction->action_name}}   </td>
       
            <td style="text-align:center">{{$dismantle->old_site}}</td>
    
            <td style="text-align:center">{{date('d-m-y', strtotime($dismantle->created_at))}}</td>
          
            <td style="text-align:center">{{$dismantle->user_name}}</td>
            
            
            <td style="text-align:center">{{$dismantle->rm}}</td>

          @endforeach
        </table>


        

                
                </div>
               
            </div>
        </div>
    </div>


    </div>

<script>

    var table =$('#example').DataTable({
        orderCellsTop: true,
       fixedHeader: true,
       dom: 'Bfrtip',       
buttons: ['excel']
    });
</script>



@endsection

resources/views/cabinets/edit.blade.php
@extends('layouts.app')
@section('content')
@if ($message=Session::get('success'))


<div class="container">
    <div class="alert alert-primary" role="alert">
        {{$message}}
    </div>
</div>
@endif
<form action="{{route('cabinets.update',$cabinet->id)}}" method="POST">
    @csrf
    @method('PUT')
    @if ($errors->any())


    <div class="alert alert-danger">
       <ul>
           @foreach ($errors->all() as $error)
               <li>{{ $error }}</li>
           @endforeach
       </ul>
    </div>

    @endif
<div class="raw">
    <div class="column">

      


        
            <div class="col-xs-12 col-sm-12 col-md-12">
<div class="form-group">
                <strong>Cabinet name:</strong>
              
                <input type="text" name="cabinet_name" 

value="{{$cabinet->cabinet_name}}"
class="form-control" required>
            </div>
            </div>
       
           
            </div>
            <div class="column">
     
            <div class="col-xs-12 col-sm-12 col-md-12">
<div class="form-group">
                <strong>Oracle code:</strong>
              
                <input type="text" name="oracle_code"

value="{{$cabinet->oracle_code}}"
class="form-control" required>
            </div>
            </div>
          

       
        
</div>

<div class="pull-right">
<button class="button" type="submit" >Update</button>
</div>
</form>
@endsection

resources/views/cabinets/import.blade.php
@extends('layouts.app')
@section('content')
<div class="container mt-5">
 
   
  @if(session('status'))
    <div class="alert alert-success">
        {{ session('status') }}
    </div>
  @endif
 
  <div class="card">
 
    <div class="card-header font-weight-bold">
      <h2 class="float-left">  <p>Import the Cabinet file</p> </h2>
   
    </div>
 
    <div class="card-body">
 
        <form id="excel-csv-import-form" method="POST"  action="{{ url('import-cabinet') }}" accept-charset="utf-8" enctype="multipart/form-data">
 
          @csrf
                   


          @if (count($errors) > 0)
                <div class="row">
                    <div class="col-md-8 col-md-offset-1">
                      <div class="alert alert-danger alert-dismissible">
                          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">okay!!</button>
                          <h4><i class="icon fa fa-ban"></i> Sorry!</h4>
                          @foreach($errors->all() as $error)
                          {{ $error }} <br>
                          @endforeach      
                      </div>
                    </div>
                </div>
                @endif



            <div class="row">
 
                <div class="col-md-12">
                    <div class="form-group">
                        <input type="file" name="file" placeholder="Choose file">
                    </div>
                    @error('file')
                        <div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
                    @enderror
                </div>              
  
                <div class="col-md-12">
                    <button type="submit" class="btn btn-primary" id="submit"> Import </button>
                </div>
            </div>     
        </form>
 
    </div>
 
  </div>
 
</div>  

@endsection

resources/views/cabinets/index.blade.php
@extends('layouts.app')
@section('content')
@if ($message=Session::get('success'))


<div class="container">
    <div class="alert alert-primary" role="alert">
        {{$message}}
    </div>
</div>
@endif
<center>
        <h3 class="header">Cabinets Information</h3>
      
    </center>
    <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <h4>
                            <div class="pull-right">
                         @can('create')
                            <a href="{{route('cabinets.create')}}">    <button type="button" class="btn btn-outline-success" >Add new cabinet</button></a>
                            @endcan
                            @can('track')
                            <a href="{{route('cabinet_track')}}">    <button type="button" class="btn btn-outline-success" >Track</button></a>
                            @endcan
                            @can('admin')
                            <a href="{{route('cabinetactions')}}">    <button type="button" class="btn btn-outline-success" >Action</button></a>
                            @endcan
                            <a href="{{route('cabinetwarehouse')}}">    <button type="button" class="btn btn-outline-success" >Cabinet in warehouse</button></a>
                        </h4>
               
                        <h6>
   
                          
                        <div class="dropdown">
  <button class="btn btn-outline-danger" >Cabinet Actions</button>
  <div id="myDropdown" class="dropdown-content">
    <a href="/cabinet/install">Installation</a>
    <a href="/cabinet/reshuffling">Reshuffling</a>
    <a href="/cabinet/dismantle">Dismantle</a>
  </div>
</div>
            
                        </h6>
                  
                       
                    </div>
                    <div class="card-body">

                        <table class="table table-bordered table-striped" id="example" width="100%">
                            <thead>
                                <tr>


                                <th style="text-align:center" class="formTableTitle" style="text-align:center" nowrap ><span class="tableheadtext" >ID</span> </th>
                                <th style="text-align:center" class="formTableTitle" style="text-align:center" nowrap ><span class="tableheadtext" >Site code</span> </th>
            <th style="text-align:center" class="formTableTitle" style="text-align:center" nowrap ><span class="tableheadtext" >Type</span> </th>
            <th style="text-align:center" class="formTableTitle" style="text-align:center" nowrap ><span class="tableheadtext" >Status</span> </th>
            <th style="text-align:center" class="formTableTitle" style="text-align:center" nowrap ><span class="tableheadtext" >Oracle code</span> </th>
            

            <th style="text-align:center" class="formTableTitle" style="text-align:center" nowrap ><span class="tableheadtext" >Installation date</span> </th>
            @can('delete')
            <th style="text-align:center" class="formTableTitle" style="text-align:center" nowrap ><span class="tableheadtext" >Delete</span> </th>
            @endcan
            @can('edit')
            <th style="text-align:center" class="formTableTitle" style="text-align:center" nowrap ><span class="tableheadtext" >Edit</span> </th>
            @endcan
            <tbody>
            @foreach ($cabinets as $cabinet)
            <tr>
            <td style="text-align:center">{{$cabinet->id}}</td>
            <td style="text-align:center">{{$cabinet->site->site_code}}</td>
            <td style="text-align:center">{{$cabinet->cabinet_name}}</td>
            <td style="text-align:center">{{$cabinet->is_used}}</td>
            <td style="text-align:center">{{$cabinet->oracle_code}}</td>
   
            <td style="text-align:center">{{$cabinet->installation_date}}</td>

            @can('delete')

            <td style="text-align:center">

            <form action="{{route('cabinets.destroy',$cabinet->id)}}" method="Post">
          
                    @csrf
                    @method('DELETE')
                    <button type="submit" onclick="return confirm('Are you sure you want to delete this item?');" class='bi bi-trash'  style='color: red' style="font-size: 19px;   color: rgb(255, 0, 0);" ></button>
                    </form>

</td>

@endcan
@can('edit')  

<td style="text-align:center">
          <a class='fa fa-edit' style='color: #00678f' style="font-size: 19px;   color: rgb(255, 0, 0);" href="{{route('cabinets.edit',$cabinet->id)}}"></a> 
        </td>
        @endcan
                    
                
                
                


            @endforeach
        </table>
     






             <script>


    $(document).ready(function() {
   

        
   

   var table = $('#example').DataTable( {
           
       orderCellsTop: true,
       fixedHeader: true,
       dom: 'Bfrtip',       
buttons: [


    {
                extend: 'excel',
                exportOptions: {
                    columns: ':visible'
                }},
    'colvis'

],

columns: [
{data: 'id', name: 'id'},
{data: 'site_code', orderable: false,},
{data: 'type', orderable: false,},
{data: 'used', orderable: false},
{data: 'oracle_code', orderable: false},

{data: 'date', orderable: false},
@can('delete')
{data: 'Delete', orderable: false},
@endcan
@can('edit')
{data: 'Edit', orderable: false},
@endcan


]
   });
});




  </script>
 
 
        </div>
                </div>
            </div>
        </div>
    </div>


</div>


@endsection

resources/views/cabinets/show.blade.php
@extends('layouts.app')
@section('content')
@if ($message=Session::get('no'))


<div class="container">
    <div class="alert alert-primary" role="alert">
        {{$message}}
    </div>
</div>
@endif

<form action="{{route('cabinets.show',$cabinet->id)}}" method="GET">

@csrf

<table class="table table-bordered">

    <tr>

      <th scope="col">type</th>
      <th scope="col">Number</th>
      <th scope="col">Oracle Code</th>
      <th scope="col">is used</th>
      <th scope="col">Add new</th>
    </tr>

  <tbody>
  <tr>
         <td>{{$cabinet->cabinet_name}}</td>
         <td>{{$cabinet->number}}</td>
         <td>{{$cabinet->oracle_code}}</td>
         <td>{{$cabinet->used}}</td>

          <td>   



             


          <a href="{{route('count',$cabinet->id)}}"> <i class="material-icons" style="font-size:20px;color:red">add_circle_outline</i></a> 

        </td>
  </tr>
        </form>


@endsection