routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use Illuminate\Http\Request;

/*Route::group(['middleware' => ['role:user']], function () {


});*/
Route::get('test-notification', 'HomeController@sendToken');
Route::post('/', 'HomeController@storeToken')->name('send');
Route::post('forget-password','auth\ForgotPasswordController@submitForgetPasswordForm')->name('forget.password.post'); 
Route::get('passwords/reset', 'auth\ForgotPasswordController@showForgetPasswordForm')->name('forget.password.get');
Route::get('reset-password/{token}', 'auth\ForgotPasswordController@showResetPasswordForm')->name('reset.password.get');
Route::post('reset-password', 'auth\ForgotPasswordController@submitResetPasswordForm')->name('reset.password.post');
Route::get('/mark-as-read', 'auth\ForgotPasswordController@markAsRead')->name('mark-as-read');

        Auth::routes();

        Route::post('sitecodename', 'SiteController@siteCodeName')->name('sitecodename');
        Route::post('lo', [App\Http\Controllers\loController::class, 'logout'])->name('lo');

       

        Route::group(['middleware' => ['auth']], function() {
            Route::get('solars/{solar}/e', 'SolarController@editnumber');
            Route::post('solar/s', 'SolarController@updatenumber');
        
        Route::resource('sites', 'siteController');
        Route::get('/siteimport', 'sitecontroller@import_excel')->name('siteimport');  
        Route::get('powersolution', 'siteController@solution')->name('solution');
        Route::resource('generators', 'GeneratorController');
        Route::get('generator/warehouse', 'GeneratorController@warehouse')->name('generatorswarehouse');
        Route::get('generators/add/action', 'GeneratorController@addaction')->name('addaction');
        Route::resource('tanks', 'TankController');
        
        Route::resource('solars', 'SolarController');  
        Route::get('solar/warehouse', 'SolarController@warehouse')->name('solarswarehouse');
        Route::get('tanks/newcreate/{generator}', 'TankController@creategeneratortank')->name('newtankcreate');
        Route::post('tanks/newcreate/{generator}', 'TankController@storegeneratortank')->name('newtankscreate');
        Route::get('tanksimport', 'TankController@import_excel')->name('tanksimport');
        Route::post('import-tank', 'TankController@import');
        Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
        Route::get('/poweractions', [App\Http\Controllers\HomeController::class, 'poweractions'])->name('poweractions');
       
        Route::get('warehousesolution', 'warehouseController@solution')->name('warehoussolution');

  
        Route::resource('warehouses', 'WarehouseController');
       
        Route::get('battery/warehouse', 'BatteryController@warehose')->name('batterywarehouse');
       
        Route::post('cheack_warehouse', 'WarehouseController@cheackWarehouse')->name('cheack_warehouse');



        Route::get('cabinet/warehouse', 'CabinetController@warehouse')->name('cabinetwarehouse');
        Route::get('cabinet/shipment/create', 'CabinetController@craeteShipment')->name('ch');
       Route::post('cabinet/shipments/create', 'CabinetController@addShipment')->name('csh');

       Route::resource('batteries', 'BatteryController');

       Route::get('battery/shipment/create', 'BatteryController@craeteShipment');
       Route::post('battery/shipment', 'BatteryController@addShipment')->name('batteryshipment');
       Route::resource('cabinets', 'CabinetController');
        Route::group(['middleware' =>['role:Management']], function () {

        Route::resource('roles', 'RoleController');
        Route::resource('users', 'UserController');
        Route::get('site/track', 'AuditsController@track');
        Route::get('cabinet/track', 'AuditsController@cabinetTrack')->name('cabinet_track');
        Route::get('generator/track', 'AuditsController@index')->name('track');
        Route::get('generator/track/{generator}', 'AuditsController@trackshow')->name('generatortrack');
      
        Route::get('tank/track', 'AuditsController@tankTrack')->name('tank_track');
        Route::get('solar/track', 'AuditsController@solarTrack')->name('solar_track');

        Route::post('site/destroy/{id}',  'SiteController@des')->name('des');
        Route::get('siteexport','sitecontroller@export');
        Route::get('battery/track', 'AuditsController@batterytrack')->name('battery-track');

                                                                 });

    


    
     
        Route::resource('amperes', 'AmpereController');
      
     

        Route::get('import-file', 'HomeController@import')->name('import-file');
        Route::get('batteryimport', 'BatteryController@import_ex')->name('batteryimport');
        Route::post('import-battery', 'BatteryController@importExcelCSV');
        Route::get('generatorimport', 'GeneratorController@import_ex')->name('generatorimport');
        Route::post('import-excel-csv-file', 'GeneratorController@importExcelCSV');
        Route::get('ampereimport', 'AmpereController@import_ex')->name('ampereimport');
        Route::post('import-ampere', 'AmpereController@importExcelCSV');
       

        Route::get('solarimport', 'SolarController@import_excel')->name('solarimport');
        Route::post('import-solar', 'SolarController@import');
        Route::get('cabinet_import', 'CabinetController@import_excel')->name('cabinetimport');
        Route::post('import-cabinet', 'CabinetController@import');
       
        Route::post('import', 'sitecontroller@import');  



    Route::get('genes/{generator}/e', 'GeneratorController@editnumber');
 
    Route::post('generator/s', 'GeneratorController@updatenumber');

   
    Route::get('batts/{battery}/e', 'BatteryController@editnumber');
    Route::post('battery/s', 'BatteryController@updatenumber');
    Route::get('battery/shipment/create', 'BatteryController@craeteShipment')->name('batteryshipmentcreate');
 
    Route::get('in', 'GeneratorController@in');

   

    Route::post('tabledit/action', 'GeneratorController@action')->name('tabledit.action');
    Route::get('searchform', [App\Http\Controllers\GeneratorController::class,'compare'])->name('searchform');
   /* Route::get('searchform', 'GeneratorController@form');*/

    Route::get('searchs', 'GeneratorController@search')->name('searchs');

    Route::get('cabinet/dismantle', 'GeneratorpoweractionController@cabinetDismantle');
    Route::get('cabinet/reshuffling', 'GeneratorpoweractionController@cabinetReshuffling');
    Route::get('cabinet/install', 'GeneratorpoweractionController@cabinetInstall');



    Route::get('sitesearch', [App\Http\Controllers\siteController::class,'search'])->name('sitesearch');
    
 
    Route::get('reshuffling', 'GeneratorpoweractionController@reshuffling')->name('re');
    Route::get('dismantle', 'GeneratorpoweractionController@dismantle')->name('dismantle');
    Route::get('battery/dismantle', 'GeneratorpoweractionController@batteryDismantle')->name('bdismantle');
    Route::get('battery/reshuffling', 'GeneratorpoweractionController@batteryReshuffling')->name('bre');
    Route::get('install', 'GeneratorpoweractionController@install')->name('install');
    Route::get('battery/install', 'BatteryController@install')->name('batteryinstall');
    Route::get('solar/install', 'SolarController@install')->name('solarinstall');
    Route::get('poweractions/create/', 'GeneratorpoweractionController@create')->name('powercreate');
    Route::put('/poweractions/create', 'GeneratorpoweractionController@store')->name('powerscreate');
    Route::put('/poweractions/create/rep', 'GeneratorpoweractionController@storee')->name('powerscreaterep');
  //  Route::put('/poweractions/reinstall', 'GeneratorpoweractionController@reinstall')->name('reinstall');
    Route::put('/poweractions/create/battery', 'GeneratorpoweractionController@batterystore')->name('powerscreatebattery');
   
    Route::get('generator/shipment/create', 'GeneratorController@craeteShipment')->name('shipmentcreate');
    Route::get('solar/shipment/create', 'SolarController@craeteShipment')->name('solarshipmentcreate');
    Route::post('solar/shipment', 'solarController@addShipment')->name('solarshipment');
    Route::post('generator/shipment', 'GeneratorController@addShipment')->name('shipment');
  

    Route::get('poweraction', [App\Http\Controllers\GeneratorController::class,'powerAction'])->name('poweraction');
  
   
    Route::resource('gene', 'AuditsController');
 
    Route::get('ampere/track', 'AuditsController@amperetrack');
   
    Route::get('/users/{id}/password', 'UserController@password')->name('editpassword');
    Route::post('/users/{id}/password', 'UserController@changePassword')->name('userpassword');

    Route::get('cabinetactions', 'CabinetController@actions')->name('cabinetactions');
    Route::get('bactions', 'BatteryController@actions')->name('bactions');
    Route::get('solar/actions', 'SolarController@addaction')->name('solaractions');



    Route::delete('tanks/{tank}','TankController@destroy')->name('tankdes');
  

 

    
 



});


Route::get('/p', [App\Http\Controllers\siteController::class, 'test']);



 Route::get('oi', 'sitecontroller@exportt');
 Route::post('oi', 'sitecontroller@exportt');
 Route::get('generator/export/',  'GeneratorController@export')->name('geneexport');

 Route::get('cabinets/{cabinet}/e', 'CabinetController@editnumber');
 Route::post('cabinets/s', 'CabinetController@updatenumber');

 Route::get('dismantle/{generator}/e', 'generatorController@editdismantle');
 Route::post('dismantle/s', 'generatorController@updatedismantle');
 
 Route::get('reshuffling/{generator}/e', 'generatorController@editreshuffling');
 Route::post('reshuffling/s', 'generatorController@updatereshuffling');
 Route::get('cabinetreshuffling/{cabinet}/e', 'cabinetController@editreshuffling');
 Route::post('cabinetreshuffling/s', 'cabinetController@updatereshuffling');

app/Models/Battery.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use App\Models\Site;
use App\Models\Warehouse;
use App\Models\Solar;
use App\Models\Cabinet;
use App\Models\Generatorpoweraction;
use OwenIt\Auditing\Auditable;
use OwenIt\Auditing\Contracts\Auditable as AuditableContract;
class Battery extends Model implements AuditableContract
{

    use \OwenIt\Auditing\Auditable;
    use HasFactory;
    protected $casts = [
        'installation_date' => 'date',

    ];
  
    protected $table ="batteries";
    protected $fillable =['site_id','solar','cabinet_id','battery_brand','capacity','numbers','status','oracle_code','installation_date','shipment_date','po','is_active','solar','dismantle_date'];

 


    public function __construct(array $attributes = [])
    {        

      //  $this->created([$this, 'onCreated']);
        $this->deleted([$this, 'onDeleted']);
        


        parent::__construct($attributes);
    }




    public function solar()
    {
        return $this->belongsTo(Solar::class);
    }
    

    public function site()
    {
        return $this->belongsTo(Site::class);
    }
    public function cabinet()
    {
        return $this->belongsTo(Cabinet::class);
    }
 
  
    public function warehouse()
    {
        return $this->belongsTo(Warehouse::class);
    }
  
   /* public function onDeleted(\App\Models\Battery $batteries)
    {
        if($batteries->site){
        $batteries->site->updatePowerSolutions();
$batteries->site->save();}

    }*/
  
  
  
 /* 
  public function onCreated(\App\Models\Battery $batteries)
    {
        if($batteries->site){
         $x=$batteries->numbers;

 
  $batteries->site->updatePowerSolutions($x);

        }
    }*/
    public function generatorpoweraction(  )  
    {
        return $this->hasMany(Generatorpoweraction::class);
    }
}

resources/views/batteries/create.blade.php
@extends('layouts.app')
@section('content')
@if ($errors->any())

<div class="alert alert-danger">
   <ul>
       @foreach ($errors->all() as $error)
         

       <li>   {{ $error }}</li>
       @endforeach
   </ul>
</div>
@endif

<form action="{{route('batteries.store')}}" method="POST">
    @csrf
    <div class="raw">
<div class="column">

        <div class="form-group">
            <strong>Site Code:</strong>


                <input type="text" name="site_code" class="form-control" id="site_code" placeholder="Site code" required>
                <span id="error-message" style="color: red; display: none;">* the site is not available *</span>
        </div>

        <div class="form-group">
        <strong>Cabinet ID:</strong>

        <select name="cabinet_id" class="form-control" id="cabinet_id" placeholder="Cabinet id">
        <option value="">Select</option>
        
</select>

    </div>
    
            <div class="form-group">

                <strong>Battery brand:</strong>
                <input type="text" name="battery_brand" class="form-control" placeholder="Battery Brand" required>


            </div>


            <div class="form-group">
                <strong>Capacity:</strong>
                <input type="number" name="capacity" class="form-control" placeholder="Capacity" required>


        </div>
   
            <div class="form-group">
                <strong>Numbers:</strong>
                <input type="number" name="numbers" class="form-control" placeholder="Numbers" required>

            </div>
       

    
            <div class="form-group">
                <strong>PO:</strong>
                <input type="number" name="po" class="form-control" placeholder="po" required>

            </div>

    </div>



    <div class="column">




    <div class="form-group">
    <strong>Status:</strong>
            <select type="text" name="status" class="form-control" placeholder="status" required >
            <option value="">Select</option>

        <option >Used</option>
        <option >New</option>

    </select>


    </div>



      
        <div class="form-group">
        <strong>Solar ID:</strong>
        <Select type="name" name="solar" class="form-control" placeholder="solar id" id ="solar_id">
            <option value="">Select</option>
</Select>

    </div>

    <div class="form-group">
        <strong>Installation date:</strong>
        <input type="date" name="installation_date" class="form-control" placeholder="installation_date" required>

    </div>


    <div class="form-group">
        <strong>PR:</strong>
        <input type="number" name="pr" class="form-control" placeholder="PR " required>

    </div>




    <div class="form-group">
                <strong>Oracle Code:</strong>
                <input type="text" name="oracle_code" class="form-control" placeholder="Oracle Code" required>

            </div>


<div class="pull-right">
    <button class="button">create</button>
   </div>
    </div>

</div>


</form>
</div>
</div>
<script>

    $(document).ready(function(){

        $('#site_code').blur(function() {

            var siteCode = $(this).val();
            $.ajax({
            url: "{{ route('cheack_site') }}",
            method: 'POST',
            data: {
                _token: "{{ csrf_token() }}",
                site_code: siteCode
            },
            dataType:'json',
         
            success: function(response) {
           if(response.b){
            
           }
              if(response.a){
                $('#error-message').hide();
              }
              else{
                $('#error-message').show();
      
            document.getElementById("site_code").value="";

              }
            
    },

        });

   
    });});
</script>
<script>


$("#site_code").on('change', function(){
        var siteCode = $(this).val();
        var option = '<option value="">Select</option>';
        $('#cabinet_id').html(option);
        $('#solar_id').html(option);
        $.ajax({
            
    url: "{{ route('cheack_cabinet') }}",
            method: 'POST',
            data: {
                _token: "{{ csrf_token() }}",
                site_code: siteCode
            },
            dataType:'json',
         
            success: function(response) {
                var option = '<option value="">Select</option>';
           console.log(response );

           
           for (var i=0;i<response.length;i++){

      
    option += '<option value="'+ response[i].id + '">' + response[i].id + '</option>';
       $('#cabinet_id').html(option);
    }
  
   

              
            
    },

        });

        $.ajax({
            
            url: "{{ route('cheack_solar') }}",
                    method: 'POST',
                    data: {
                        _token: "{{ csrf_token() }}",
                        site_code: siteCode
                    },
                    dataType:'json',
                 
                    success: function(response) {
                        var option = '<option value="">Select</option>';
                   console.log(response );
        
                   
                   for (var i=0;i<response.length;i++){
        
              
            option += '<option value="'+ response[i].id + '">' + response[i].id + '</option>';
               $('#solar_id').html(option);
            }
          
           
        
                      
                    
            },
        
                });
        





        });
</script>
@endsection

resources/views/batteries/createwarehouse.blade.php
@extends('layouts.app')
@section('content')

@if ($errors->any())

<div class="alert alert-danger">
   <ul>
       @foreach ($errors->all() as $error)
           <li>

            {{ $error }}</li>
       @endforeach
   </ul>
</div>
@endif







<form action="{{route('batteryshipment')}}" method="POST" id="myForm">
    @csrf
    <div class="raw">
<div class="column">




            <div class="form-group">
                <strong>Warehouse  name:</strong>
                <input type="text" name="warehouse_name" id="warehouse_name"class="form-control" placeholder="Warehose" required>
                <span id="error-message" style="color: red; display: none;">* the warehouse is not available *</span>
            </div>
            

            <div class="form-group">
            <strong>Capacity:</strong>
            <select class="form-control" name="capacity"  id="capacity" placeholder="Capacity" required >
            <option value="">Select capacity</option>

        <option >8</option>
        <option >15</option>
        <option >17</option>
        <option >20</option>
        <option >22</option>
    </select>


    </div>


            <div class="form-group">
        <strong>Numbers:</strong>
        <input type="text" name="numbers" class="form-control" placeholder="numbers" required>

    </div>

  
    <div class="form-group">
        <strong>Shipment date:</strong>
        <input type="date" name="shipment_date" class="form-control" placeholder="Shipment date" required>

    </div>
</div>
<div class="column">

<div class="form-group">
        <strong>Status:</strong>
        <select class="form-control" name="status"   placeholder="Is uesed!" required >
        <option value="">Select status</option>

        <option >Uesed</option>
        <option >New</option>
  
    </select>

</div>



<div class="form-group">
    <strong>Oracle code :</strong>
    <input type="number" name="oracle_code" class="form-control" placeholder="Oracle code" required>

</div>



<div class="form-group">
    <strong>Battery brand :</strong>
    <input type="text" name="battery_brand" class="form-control" placeholder="Battery brand" required>

</div>
<div class="form-group">
    <strong>Process order :</strong>
    <input type="number" name="po" class="form-control" placeholder="PO..." required>

</div>
</div>





<div class="pull-right">

    <button class="button" type="submit" >Add</button>
   </div>
    </div>

</div>


</form>
</div>
</div>

<script>
    $("#warehouse_name").on('change',function(){

 var warehouseName= $(this).val();
 console.log(warehouseName);
 $.ajax({
    url: "{{ route('cheack_warehouse') }}",
    method: 'POST',
            data: {
                _token: "{{ csrf_token() }}",
                warehouse_name:warehouseName
            },
            dataType:'json',
         
            success: function(response) {
        
              if(response.a){
               
                $('#error-message').hide();
              
              }
              if(response.b){
        
                $('#error-message').show();
      
            document.getElementById("warehouse_name").value="";

              }
            
    },
 });

    });
</script>
@endsection

resources/views/batteries/edit.blade.php
@extends('layouts.app')
@section('content')
@if ($message=Session::get('success'))


<div class="container">
    <div class="alert alert-primary" role="alert">
        {{$message}}
    </div>
</div>
@endif
<form action="{{route('batteries.update',$battery->id)}}" method="POST">
    @csrf
    @method('PUT')
    @if ($errors->any())


    <div class="alert alert-danger">
       <ul>
           @foreach ($errors->all() as $error)
               <li>{{ $error }}</li>
           @endforeach
       </ul>
    </div>

    @endif
<div class="raw">
    <div class="column">

      


        
            <div class="col-xs-12 col-sm-12 col-md-12">
<div class="form-group">
                <strong>Battery brand:</strong>
              
                <input type="text" name="battery_brand"

value="{{$battery->battery_brand}}"
class="form-control" placeholder="Battery Brand" required>
            </div>
            </div>
            
            <div class="col-xs-12 col-sm-12 col-md-12">
<div class="form-group">
                <strong>Capacity:</strong>
              
                <input type="number" name="capacity"

value="{{$battery->capacity}}"
class="form-control" placeholder="Capacity"  required>
            </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Cabinet ID:</strong>
                @if($battery->cabinet_id !='') 
                <select type="number" name="cabinet_id" class="form-control" value="{{$battery->cabinet_id}}">

                @foreach($cabinet as $cab)
                <option value="{{$cab->id}}">{{$cab->id}}</option>
                @endforeach
                <option value="">Null</option>
                </select>
@else
<select type="number" name="cabinet_id" class="form-control" >
<option value="">Null</option>
                @foreach($cabinet as $cab)
                <option value="{{$cab->id}}">{{$cab->id}}</option>
                @endforeach
                
                </select>
                @endif
            </div>
            </div>
            </div>
            <div class="column">
          
            <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Oracle code:</strong>
              
                <input type="number" name="oracle_code"

value="{{$battery->oracle_code}}"
class="form-control" placeholder="Oracle Code" required>
            </div>
            </div>
            
            <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Solar ID:</strong>
                @if($battery->solar =='')      
                <select type="number" name="solar" class="form-control">
                <option value="">Null</option>
                @foreach($solar as $sol)
                <option value="{{$sol->id}}">{{$sol->id}}</option>
                @endforeach
                
                </select>
                @else

                <select type="number" name="solar" class="form-control"  value="{{$battery->solar}}">
          
                @foreach($solar as $sol)
                <option value="{{$sol->id}}">{{$sol->id}}</option>
                
                @endforeach
                <option value="">Null</option>
                </select>
@endif
            </div>
            </div>
</div>

<div class="pull-right">
<button class="button" type="submit" >Update</button>
</div>
</form>
@endsection

resources/views/batteries/index.blade.php
@extends('layouts.app')
@section('content')
@if ($message=Session::get('success'))


<div class="container">
    <div class="alert alert-primary" role="alert">
        {{$message}}
    </div>
</div>
@endif
<center>
        <h3 class="header">  <p> Batteries in site</p></h3>

    </center>

    <div class="row">
 
 <div class="col-md-12">
     <div class="card">
         <div class="card-header">
       
             <h4>
             <div class="u">
                 <div class="pull-right">
                    @can('track')
                 <a href="{{route('battery-track')}}">       <button type="button" class="btn btn-outline-success">Track</button></a>
                 @endcan
                 @can('create')
                     <a href="{{route('batteries.create')}}">    <button type="button" class="btn btn-outline-success" >Add new Battery</button></a>
                    @endcan
                     <a href="{{route('batterywarehouse')}}">    <button  class="btn btn-outline-success" type="submit">Warehouse</button></a>
                     <a href="{{route('bactions')}}">    <button  class="btn btn-outline-success" type="submit">Add action</button></a>

</div>
             </h4>

             <h6>      
             <div class="dropdown">
  <button class="btn btn-outline-danger" >Batteries actions</button>
  <div id="myDropdown" class="dropdown-content">
    <a href="{{route('batteryinstall')}}">Installation</a>
    <a href="{{route('bre')}}">Reshuffling</a>
    <a href="{{route('bdismantle')}}">Dismantle</a>
  </div>
</div>


             </h6>
            
         </div>
               
         <div class="card-body">
         <div class="cont">

<table  class="table table-bordered table-striped data-table" width="100%"  >
<thead>
 <tr>
 <th>ID</th>
    <th>Site code</th>
    <th>Battery brand</th>
    <th>Capacity</th>
    <th>Battery numbers</th>
     <th>Cabinet type</th>

     <th>Solar ID</th>
  
    
     <th>PO</th>
    

   
    
   
     @can('edit')
     <td> <p>Edit</p> </td>
    
     @endcan
     @can('delete')
     <td> <p>Delete</p> </td>
     @endcan
     </tr>
        <tbody>
            @foreach ($battery as $v)
            <tr>
            <td style="text-align:center">{{$v->id}}</td>
            <td style="text-align:center">{{$v->site->site_code}}</td>
            <td style="text-align:center">{{$v->battery_brand}}</td>
            <td style="text-align:center">{{$v->capacity}}</td>
            <td style="text-align:center">{{$v->numbers}}</td>
            <td style="text-align:center"> @if($v->cabinet){{$v->cabinet->cabinet_name}}@endif</td>
            
        
            <td style="text-align:center">{{$v->solar}}</td>
          
           
            <td style="text-align:center">{{$v->po}}</td>
          
      


            @can('edit')  
            <td style="text-align:center">   
            
            <a class='fa fa-edit' style='color: #00678f' style="font-size: 19px;   color: rgb(255, 0, 0);" href="{{route('batteries.edit',$v->id)}}"></a>
            </td>
            @endcan
            
            @can('delete')  
            <td style="text-align:center">  
            <form action="{{route('batteries.destroy',$v->id)}}" method="Post">
              
          @csrf
          @method('DELETE')     
        
                <button  type="submit"  class='bi bi-trash'  style='color: red' style="font-size: 19px;   color: rgb(255, 0, 0);" onclick="return confirm('Are you sure you want delete the battery?')" ></button>
</form>
         </td>
         @endcan
</tr>
            @endforeach
        </table>
</div>
</div>



<script>
   $(document).ready(function() {
    
   

            $('.data-table thead tr').clone(true).appendTo( '.data-table thead' );
            
            $('.data-table thead tr:eq(1) th').each( function (i) {

                var title = $(this).text();

                $(this).html( '<input type="text" placeholder=" Search '+title+'" />' );
              
                $( 'input', this ).on( 'keyup change', function () {
                    if ( table.column(i).search() !== this.value ) {
                        table
                         .column(i)
                            .search( this.value )
                            .draw();
                    }
                });
            });
   
            var table = $('.data-table').DataTable( {
                 
                orderCellsTop: true,
                fixedHeader: true,
                dom: 'Bfrtip',       
                
        buttons: [
           
    {
                extend: 'excel',
                exportOptions: {
                    columns: ':visible'
                }},
                {
                extend:  'csv',
                exportOptions: {
                    columns: ':visible'
                }},
                {
                extend:  'pdf', 
                exportOptions: {
                    columns: ':visible'
                }},
                {
                extend:  'copy',
                exportOptions: {
                    columns: ':visible'
                }},
                
                'colvis'
   ],
   columnDefs: [ {
            targets:[-1,-2,-3,-10],
            visible: false
        } ],
        columns: [
            {data: 'id', name: 'id'},
    {data: 'site_code', name: 'site_code'},
    {data: 'battery_brand', name: 'battery_brand'},
    {data: 'capacity', name: 'capacity'},
    {data: 'numbers', name: 'numbers'},
    {data: 'cabinet_name', name: 'cabinet_name'},
    {data: 'solar', name: 'solar'},
  

    {data: 'po', name: 'po'},
  


   
    @can('edit')  
    {data: 'edit',   name: 'actions'},
@endcan
   
@can('delete')  
{data: 'delete',   name: 'actions'},
@endcan
        ]
            });
        });
        
    </script>


@endsection