routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use Illuminate\Http\Request;

/*Route::group(['middleware' => ['role:user']], function () {


});*/
Route::get('test-notification', 'HomeController@sendToken');
Route::post('/', 'HomeController@storeToken')->name('send');
Route::post('forget-password','auth\ForgotPasswordController@submitForgetPasswordForm')->name('forget.password.post'); 
Route::get('passwords/reset', 'auth\ForgotPasswordController@showForgetPasswordForm')->name('forget.password.get');
Route::get('reset-password/{token}', 'auth\ForgotPasswordController@showResetPasswordForm')->name('reset.password.get');
Route::post('reset-password', 'auth\ForgotPasswordController@submitResetPasswordForm')->name('reset.password.post');
Route::get('/mark-as-read', 'auth\ForgotPasswordController@markAsRead')->name('mark-as-read');

        Auth::routes();

        Route::post('sitecodename', 'SiteController@siteCodeName')->name('sitecodename');
        Route::post('lo', [App\Http\Controllers\loController::class, 'logout'])->name('lo');

       

        Route::group(['middleware' => ['auth']], function() {
            Route::get('solars/{solar}/e', 'SolarController@editnumber');
            Route::post('solar/s', 'SolarController@updatenumber');
        
        Route::resource('sites', 'siteController');
        Route::get('/siteimport', 'sitecontroller@import_excel')->name('siteimport');  
        Route::get('powersolution', 'siteController@solution')->name('solution');
        Route::resource('generators', 'GeneratorController');
        Route::get('generator/warehouse', 'GeneratorController@warehouse')->name('generatorswarehouse');
        Route::get('generators/add/action', 'GeneratorController@addaction')->name('addaction');
        Route::resource('tanks', 'TankController');
        
        Route::resource('solars', 'SolarController');  
        Route::get('solar/warehouse', 'SolarController@warehouse')->name('solarswarehouse');
        Route::get('tanks/newcreate/{generator}', 'TankController@creategeneratortank')->name('newtankcreate');
        Route::post('tanks/newcreate/{generator}', 'TankController@storegeneratortank')->name('newtankscreate');
        Route::get('tanksimport', 'TankController@import_excel')->name('tanksimport');
        Route::post('import-tank', 'TankController@import');
        Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
        Route::get('/poweractions', [App\Http\Controllers\HomeController::class, 'poweractions'])->name('poweractions');
       
        Route::get('warehousesolution', 'warehouseController@solution')->name('warehoussolution');

  
        Route::resource('warehouses', 'WarehouseController');
       
        Route::get('battery/warehouse', 'BatteryController@warehose')->name('batterywarehouse');
       
        Route::post('cheack_warehouse', 'WarehouseController@cheackWarehouse')->name('cheack_warehouse');



        Route::get('cabinet/warehouse', 'CabinetController@warehouse')->name('cabinetwarehouse');
        Route::get('cabinet/shipment/create', 'CabinetController@craeteShipment')->name('ch');
       Route::post('cabinet/shipments/create', 'CabinetController@addShipment')->name('csh');

       Route::resource('batteries', 'BatteryController');

       Route::get('battery/shipment/create', 'BatteryController@craeteShipment');
       Route::post('battery/shipment', 'BatteryController@addShipment')->name('batteryshipment');
       Route::resource('cabinets', 'CabinetController');
        Route::group(['middleware' =>['role:Management']], function () {

        Route::resource('roles', 'RoleController');
        Route::resource('users', 'UserController');
        Route::get('site/track', 'AuditsController@track');
        Route::get('cabinet/track', 'AuditsController@cabinetTrack')->name('cabinet_track');
        Route::get('generator/track', 'AuditsController@index')->name('track');
        Route::get('generator/track/{generator}', 'AuditsController@trackshow')->name('generatortrack');
      
        Route::get('tank/track', 'AuditsController@tankTrack')->name('tank_track');
        Route::get('solar/track', 'AuditsController@solarTrack')->name('solar_track');

        Route::post('site/destroy/{id}',  'SiteController@des')->name('des');
        Route::get('siteexport','sitecontroller@export');
        Route::get('battery/track', 'AuditsController@batterytrack')->name('battery-track');

                                                                 });

    


    
     
        Route::resource('amperes', 'AmpereController');
      
     

        Route::get('import-file', 'HomeController@import')->name('import-file');
        Route::get('batteryimport', 'BatteryController@import_ex')->name('batteryimport');
        Route::post('import-battery', 'BatteryController@importExcelCSV');
        Route::get('generatorimport', 'GeneratorController@import_ex')->name('generatorimport');
        Route::post('import-excel-csv-file', 'GeneratorController@importExcelCSV');
        Route::get('ampereimport', 'AmpereController@import_ex')->name('ampereimport');
        Route::post('import-ampere', 'AmpereController@importExcelCSV');
       

        Route::get('solarimport', 'SolarController@import_excel')->name('solarimport');
        Route::post('import-solar', 'SolarController@import');
        Route::get('cabinet_import', 'CabinetController@import_excel')->name('cabinetimport');
        Route::post('import-cabinet', 'CabinetController@import');
       
        Route::post('import', 'sitecontroller@import');  



    Route::get('genes/{generator}/e', 'GeneratorController@editnumber');
 
    Route::post('generator/s', 'GeneratorController@updatenumber');

   
    Route::get('batts/{battery}/e', 'BatteryController@editnumber');
    Route::post('battery/s', 'BatteryController@updatenumber');
    Route::get('battery/shipment/create', 'BatteryController@craeteShipment')->name('batteryshipmentcreate');
 
    Route::get('in', 'GeneratorController@in');

   

    Route::post('tabledit/action', 'GeneratorController@action')->name('tabledit.action');
    Route::get('searchform', [App\Http\Controllers\GeneratorController::class,'compare'])->name('searchform');
   /* Route::get('searchform', 'GeneratorController@form');*/

    Route::get('searchs', 'GeneratorController@search')->name('searchs');

    Route::get('cabinet/dismantle', 'GeneratorpoweractionController@cabinetDismantle');
    Route::get('cabinet/reshuffling', 'GeneratorpoweractionController@cabinetReshuffling');
    Route::get('cabinet/install', 'GeneratorpoweractionController@cabinetInstall');



    Route::get('sitesearch', [App\Http\Controllers\siteController::class,'search'])->name('sitesearch');
    
 
    Route::get('reshuffling', 'GeneratorpoweractionController@reshuffling')->name('re');
    Route::get('dismantle', 'GeneratorpoweractionController@dismantle')->name('dismantle');
    Route::get('battery/dismantle', 'GeneratorpoweractionController@batteryDismantle')->name('bdismantle');
    Route::get('battery/reshuffling', 'GeneratorpoweractionController@batteryReshuffling')->name('bre');
    Route::get('install', 'GeneratorpoweractionController@install')->name('install');
    Route::get('battery/install', 'BatteryController@install')->name('batteryinstall');
    Route::get('solar/install', 'SolarController@install')->name('solarinstall');
    Route::get('poweractions/create/', 'GeneratorpoweractionController@create')->name('powercreate');
    Route::put('/poweractions/create', 'GeneratorpoweractionController@store')->name('powerscreate');
    Route::put('/poweractions/create/rep', 'GeneratorpoweractionController@storee')->name('powerscreaterep');
  //  Route::put('/poweractions/reinstall', 'GeneratorpoweractionController@reinstall')->name('reinstall');
    Route::put('/poweractions/create/battery', 'GeneratorpoweractionController@batterystore')->name('powerscreatebattery');
   
    Route::get('generator/shipment/create', 'GeneratorController@craeteShipment')->name('shipmentcreate');
    Route::get('solar/shipment/create', 'SolarController@craeteShipment')->name('solarshipmentcreate');
    Route::post('solar/shipment', 'solarController@addShipment')->name('solarshipment');
    Route::post('generator/shipment', 'GeneratorController@addShipment')->name('shipment');
  

    Route::get('poweraction', [App\Http\Controllers\GeneratorController::class,'powerAction'])->name('poweraction');
  
   
    Route::resource('gene', 'AuditsController');
 
    Route::get('ampere/track', 'AuditsController@amperetrack');
   
    Route::get('/users/{id}/password', 'UserController@password')->name('editpassword');
    Route::post('/users/{id}/password', 'UserController@changePassword')->name('userpassword');

    Route::get('cabinetactions', 'CabinetController@actions')->name('cabinetactions');
    Route::get('bactions', 'BatteryController@actions')->name('bactions');
    Route::get('solar/actions', 'SolarController@addaction')->name('solaractions');



    Route::delete('tanks/{tank}','TankController@destroy')->name('tankdes');
  

 

    
 



});


Route::get('/p', [App\Http\Controllers\siteController::class, 'test']);



 Route::get('oi', 'sitecontroller@exportt');
 Route::post('oi', 'sitecontroller@exportt');
 Route::get('generator/export/',  'GeneratorController@export')->name('geneexport');

 Route::get('cabinets/{cabinet}/e', 'CabinetController@editnumber');
 Route::post('cabinets/s', 'CabinetController@updatenumber');

 Route::get('dismantle/{generator}/e', 'generatorController@editdismantle');
 Route::post('dismantle/s', 'generatorController@updatedismantle');
 
 Route::get('reshuffling/{generator}/e', 'generatorController@editreshuffling');
 Route::post('reshuffling/s', 'generatorController@updatereshuffling');
 Route::get('cabinetreshuffling/{cabinet}/e', 'cabinetController@editreshuffling');
 Route::post('cabinetreshuffling/s', 'cabinetController@updatereshuffling');

resources/views/warehouses/create.blade.php
@extends('layouts.app')
@section('content')
@if ($errors->any())
<div class="alert alert-danger">
   <ul>
       @foreach ($errors->all() as $error)
           <li>

            {{ $error }}</li>
       @endforeach
   </ul>
</div>
@endif
<form action="{{route('warehouses.store')}}" method="POST">

@csrf



<div class="raw">

<br><br>
<div class="card-body">
        <div class="form-group" >
            <strong>Warehouse name:</strong>


                <input type="text" name="name" class="form-control" placeholder="Warehouse name" required>
        </div>

        <div class="form-group">
        <strong>Owner:</strong>
        <input type="text" name="owner" class="form-control" placeholder="Owner" required>

    </div>
    <div class="form-group">
        <strong>Location:</strong>
        <input type="text" name="location" class="form-control" placeholder="Location" required>

    </div>
  

          
       

<div class="pull-right">
    <button class="button">create</button>
   </div>
    </div>

</div>


</form>
@endsection

resources/views/warehouses/edit.blade.php
@extends('layouts.app')
@section('content')

<form action="{{route('warehouses.update',$warehouse->id)}}" method="POST">

@csrf
    @method('PUT')

    @if ($errors->any())


<div class="alert alert-danger">
   <ul>
       @foreach ($errors->all() as $error)
           <li>{{ $error }}</li>
       @endforeach
   </ul>
</div>

@endif




<div class="raw">
  
  <div class="columnn">
  
      <div class="form-group">
          <strong>Warehouse name:</strong>
          <input type="text" name="name" value="{{$warehouse->name}}" class="form-control" required>
  
      </div>
  </div>
  <div class="columnn">
      <div class="form-group">
              <strong>Owner:</strong>
  
  
              <input type="text" name="owner" value="{{$warehouse->owner}}" class="form-control"  required>
  
          </div>
          </div>
          <div class="columnn">
      <div class="form-group">
              <strong>Location:</strong>
  
  
              <input type="text" name="location" value="{{$warehouse->location}}" class="form-control" required>
  
          </div>
          <div class="pull-right">
      <button class="button">Update</button>
     </div>
      </div>
  
  </div>
</form>
@endsection

resources/views/warehouses/index.blade.php
@extends('layouts.app')
@section('content')

@if ($message=Session::get('success'))


<div class="container">
    <div class="alert alert-primary" role="alert">
        {{$message}}
    </div>
</div>
@endif
@if(session()->get('danger'))
                        <div class="alert alert-danger">
                            {{ session()->get('danger') }}
                        </div>
                    @endif
<center>
        <h3 class="header">Warehouses Information</h3>


    </center>
<div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <h4>
                            <div class="pull-right">

                   
                                <a href="{{route('warehouses.create')}}">    <button type="button" class="btn btn-outline-success" >Add new warehouse</button></a>
                        
                               
</div>
                        </h4>
               
                        <h6>

                        <div class="dropdown">
  <button class="btn btn-outline-danger" >Warehouse equipments</button>
  <div id="myDropdown" class="dropdown-content">
    <a href="{{route('generatorswarehouse')}}">Generators</a>
    <a href="{{route('batterywarehouse')}}">Batteries</a>
    <a href="{{route('cabinetwarehouse')}}">Cabinets</a>
    <a href="{{route('solarswarehouse')}}">Solars</a>
  </div>
</div>

                        </h6>
                  
                       
                    </div>
                    <div class="card-body">

                        <table class="table table-bordered table-striped" id="example" width="100%">
                            <thead>
                                <tr>


            <th style="text-align:center" class="formTableTitle" style="text-align:center" nowrap ><span class="tableheadtext" >Warehouse name</span> </th>

            <th style="text-align:center" class="formTableTitle" style="text-align:center" nowrap ><span class="tableheadtext" >Owner</span> </th>
 
            <th style="text-align:center" class="formTableTitle" style="text-align:center" nowrap ><span class="tableheadtext" >Location</span> </th>
             
            <th style="text-align:center" class="formTableTitle" style="text-align:center" nowrap ><span class="tableheadtext" >Created at</span> </th>
            <th style="text-align:center" class="formTableTitle" style="text-align:center" nowrap ><span class="tableheadtext" >Generator </span> </th>
            <th style="text-align:center" class="formTableTitle" style="text-align:center" nowrap ><span class="tableheadtext" >Battery</span> </th>
            <th style="text-align:center" class="formTableTitle" style="text-align:center" nowrap ><span class="tableheadtext" >Solar</span> </th>

            <th style="text-align:center" class="formTableTitle" style="text-align:center" nowrap ><span class="tableheadtext" >Cabinet</span> </th>
            @can('edit')
            <th style="text-align:center" class="formTableTitle" style="text-align:center" nowrap ><span class="tableheadtext" >Edit</span> </th>
            @endcan
           
         </tr>
        <tbody>
            @foreach ($warehouses as $v)
            <tr>
          
            <td style="text-align:center">{{$v->name}}</td>

            <td style="text-align:center">{{$v->owner}}</td>
            <td style="text-align:center">{{$v->location}}</td>
            <td style="text-align:center">{{$v->created_at->format('d- m- Y')}}</td>
            <td style="text-align:center">{{$v->generator}}</td>
            <td style="text-align:center">{{$v->battery}}</td>
            <td style="text-align:center">{{$v->solar}}</td>

    
            <td style="text-align:center">{{$v->cabinet}}</td>
          @can('edit')
            <td style="text-align:center"><a  class='fa fa-edit' style='color: #00678f' style="font-size: 19px;   color: rgb(255, 0, 0);" href="{{route('warehouses.edit',$v->id)}}"></a></td>
            @endcan
          
          
            @endforeach
        </table>
     
        
</form>


                    </div>
        
        

                
                </div>
               
            </div>
        </div>
    </div>


    <script>


$(document).ready(function() {

    
    
   


var table = $('#example').DataTable( {
    



   orderCellsTop: true,
   fixedHeader: true,
   dom: 'Bfrtip',       
   buttons: [
           
           {
                       extend: 'excel',
                       exportOptions: {
                           columns: ':visible'
                       }},
                       {
                       extend:  'csv',
                       exportOptions: {
                           columns: ':visible'
                       }},
                       {
                       extend:  'pdf', 
                       exportOptions: {
                           columns: ':visible'
                       }},
                       {
                       extend:  'copy',
                       exportOptions: {
                           columns: ':visible'
                       }},
                       
                       'colvis'
          ],

columns: [
    {data: 'name', name: 'name'},
  {data: 'owner', orderable: false,},

  {data: 'location', orderable: false},
  {data: 'created_at', orderable: false},
  {data: 'generator', orderable: false},
  {data: 'battery', orderable: false},
  {data: 'solar', orderable: false},

  {data: 'cabinet', orderable: false},

@can('edit')
{  data: 'edit', orderable: false },
@endcan


        ]
});
});



$(document).ready(function(){
    
    $('.editbtn').on('click', function(){

        $('#editmodal').modal('show');
        $tr =$(this).closest('tr');
        var data= $tr.children("td").map(function(){
          return $(this).text();
        }).get();

       
        $('#generator_id').val(data[0]);
     
      
        
    });
});







</script>



<script>
 
function test(a) {
var x = a.options[a.selectedIndex].label;
if(x=='reshuffling') { $("#add_fields_placeholderValue").show();}
else{
    $("#add_fields_placeholderValue").hide();
}
}


</script>





@endsection

resources/views/warehouses/powersolution.blade.php
@extends('layouts.app')
@section('content')


<div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <h4>
                            
All sites with its power solution
                            <div class="pull-right">

</div>
                        </h4>
               
                        <h6>
                    
            
                        </h6>
                  
                       
                    </div>
                    <div class="card-body">

                        <table class="table table-bordered table-striped" id="example" width="100%">
                            <thead>
                                <tr>


            <th style="text-align:center" class="formTableTitle" style="text-align:center" nowrap ><span class="tableheadtext" >Warehouse</span> </th>

            <th style="text-align:center" class="formTableTitle" style="text-align:center" nowrap ><span class="tableheadtext" >Generator</span> </th>
            <th style="text-align:center" class="formTableTitle" style="text-align:center" nowrap ><span class="tableheadtext" >Battery</span> </th>
           
            


            
            <th style="text-align:center" class="formTableTitle" style="text-align:center" nowrap ><span class="tableheadtext" >Solar</span> </th>
            <th style="text-align:center" class="formTableTitle" style="text-align:center" nowrap ><span class="tableheadtext" >Cabinet</span> </th>

            
         </tr>
        <tbody>
            @foreach ($warehouses as $v)
            <tr>
          
            
            <td style="text-align:center">{{$v->name}}</td>
            <td style="text-align:center">{{$v->generator}}</td>
            <td style="text-align:center">{{$v->battery}}</td>
      
            <td style="text-align:center">{{$v->solar}}</td>
            <td style="text-align:center">{{$v->cabinet}}</td>
            @endforeach
        </table>
@endsection