routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use Illuminate\Http\Request;

/*Route::group(['middleware' => ['role:user']], function () {


});*/
Route::get('test-notification', 'HomeController@sendToken');
Route::post('/', 'HomeController@storeToken')->name('send');
Route::post('forget-password','auth\ForgotPasswordController@submitForgetPasswordForm')->name('forget.password.post'); 
Route::get('passwords/reset', 'auth\ForgotPasswordController@showForgetPasswordForm')->name('forget.password.get');
Route::get('reset-password/{token}', 'auth\ForgotPasswordController@showResetPasswordForm')->name('reset.password.get');
Route::post('reset-password', 'auth\ForgotPasswordController@submitResetPasswordForm')->name('reset.password.post');
Route::get('/mark-as-read', 'auth\ForgotPasswordController@markAsRead')->name('mark-as-read');

        Auth::routes();

        Route::post('sitecodename', 'SiteController@siteCodeName')->name('sitecodename');
        Route::post('lo', [App\Http\Controllers\loController::class, 'logout'])->name('lo');

       

        Route::group(['middleware' => ['auth']], function() {
            Route::get('solars/{solar}/e', 'SolarController@editnumber');
            Route::post('solar/s', 'SolarController@updatenumber');
        
        Route::resource('sites', 'siteController');
        Route::get('/siteimport', 'sitecontroller@import_excel')->name('siteimport');  
        Route::get('powersolution', 'siteController@solution')->name('solution');
        Route::resource('generators', 'GeneratorController');
        Route::get('generator/warehouse', 'GeneratorController@warehouse')->name('generatorswarehouse');
        Route::get('generators/add/action', 'GeneratorController@addaction')->name('addaction');
        Route::resource('tanks', 'TankController');
        
        Route::resource('solars', 'SolarController');  
        Route::get('solar/warehouse', 'SolarController@warehouse')->name('solarswarehouse');
        Route::get('tanks/newcreate/{generator}', 'TankController@creategeneratortank')->name('newtankcreate');
        Route::post('tanks/newcreate/{generator}', 'TankController@storegeneratortank')->name('newtankscreate');
        Route::get('tanksimport', 'TankController@import_excel')->name('tanksimport');
        Route::post('import-tank', 'TankController@import');
        Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
        Route::get('/poweractions', [App\Http\Controllers\HomeController::class, 'poweractions'])->name('poweractions');
       
        Route::get('warehousesolution', 'warehouseController@solution')->name('warehoussolution');

  
        Route::resource('warehouses', 'WarehouseController');
       
        Route::get('battery/warehouse', 'BatteryController@warehose')->name('batterywarehouse');
       
        Route::post('cheack_warehouse', 'WarehouseController@cheackWarehouse')->name('cheack_warehouse');



        Route::get('cabinet/warehouse', 'CabinetController@warehouse')->name('cabinetwarehouse');
        Route::get('cabinet/shipment/create', 'CabinetController@craeteShipment')->name('ch');
       Route::post('cabinet/shipments/create', 'CabinetController@addShipment')->name('csh');

       Route::resource('batteries', 'BatteryController');

       Route::get('battery/shipment/create', 'BatteryController@craeteShipment');
       Route::post('battery/shipment', 'BatteryController@addShipment')->name('batteryshipment');
       Route::resource('cabinets', 'CabinetController');
        Route::group(['middleware' =>['role:Management']], function () {

        Route::resource('roles', 'RoleController');
        Route::resource('users', 'UserController');
        Route::get('site/track', 'AuditsController@track');
        Route::get('cabinet/track', 'AuditsController@cabinetTrack')->name('cabinet_track');
        Route::get('generator/track', 'AuditsController@index')->name('track');
        Route::get('generator/track/{generator}', 'AuditsController@trackshow')->name('generatortrack');
      
        Route::get('tank/track', 'AuditsController@tankTrack')->name('tank_track');
        Route::get('solar/track', 'AuditsController@solarTrack')->name('solar_track');

        Route::post('site/destroy/{id}',  'SiteController@des')->name('des');
        Route::get('siteexport','sitecontroller@export');
        Route::get('battery/track', 'AuditsController@batterytrack')->name('battery-track');

                                                                 });

    


    
     
        Route::resource('amperes', 'AmpereController');
      
     

        Route::get('import-file', 'HomeController@import')->name('import-file');
        Route::get('batteryimport', 'BatteryController@import_ex')->name('batteryimport');
        Route::post('import-battery', 'BatteryController@importExcelCSV');
        Route::get('generatorimport', 'GeneratorController@import_ex')->name('generatorimport');
        Route::post('import-excel-csv-file', 'GeneratorController@importExcelCSV');
        Route::get('ampereimport', 'AmpereController@import_ex')->name('ampereimport');
        Route::post('import-ampere', 'AmpereController@importExcelCSV');
       

        Route::get('solarimport', 'SolarController@import_excel')->name('solarimport');
        Route::post('import-solar', 'SolarController@import');
        Route::get('cabinet_import', 'CabinetController@import_excel')->name('cabinetimport');
        Route::post('import-cabinet', 'CabinetController@import');
       
        Route::post('import', 'sitecontroller@import');  



    Route::get('genes/{generator}/e', 'GeneratorController@editnumber');
 
    Route::post('generator/s', 'GeneratorController@updatenumber');

   
    Route::get('batts/{battery}/e', 'BatteryController@editnumber');
    Route::post('battery/s', 'BatteryController@updatenumber');
    Route::get('battery/shipment/create', 'BatteryController@craeteShipment')->name('batteryshipmentcreate');
 
    Route::get('in', 'GeneratorController@in');

   

    Route::post('tabledit/action', 'GeneratorController@action')->name('tabledit.action');
    Route::get('searchform', [App\Http\Controllers\GeneratorController::class,'compare'])->name('searchform');
   /* Route::get('searchform', 'GeneratorController@form');*/

    Route::get('searchs', 'GeneratorController@search')->name('searchs');

    Route::get('cabinet/dismantle', 'GeneratorpoweractionController@cabinetDismantle');
    Route::get('cabinet/reshuffling', 'GeneratorpoweractionController@cabinetReshuffling');
    Route::get('cabinet/install', 'GeneratorpoweractionController@cabinetInstall');



    Route::get('sitesearch', [App\Http\Controllers\siteController::class,'search'])->name('sitesearch');
    
 
    Route::get('reshuffling', 'GeneratorpoweractionController@reshuffling')->name('re');
    Route::get('dismantle', 'GeneratorpoweractionController@dismantle')->name('dismantle');
    Route::get('battery/dismantle', 'GeneratorpoweractionController@batteryDismantle')->name('bdismantle');
    Route::get('battery/reshuffling', 'GeneratorpoweractionController@batteryReshuffling')->name('bre');
    Route::get('install', 'GeneratorpoweractionController@install')->name('install');
    Route::get('battery/install', 'BatteryController@install')->name('batteryinstall');
    Route::get('solar/install', 'SolarController@install')->name('solarinstall');
    Route::get('poweractions/create/', 'GeneratorpoweractionController@create')->name('powercreate');
    Route::put('/poweractions/create', 'GeneratorpoweractionController@store')->name('powerscreate');
    Route::put('/poweractions/create/rep', 'GeneratorpoweractionController@storee')->name('powerscreaterep');
  //  Route::put('/poweractions/reinstall', 'GeneratorpoweractionController@reinstall')->name('reinstall');
    Route::put('/poweractions/create/battery', 'GeneratorpoweractionController@batterystore')->name('powerscreatebattery');
   
    Route::get('generator/shipment/create', 'GeneratorController@craeteShipment')->name('shipmentcreate');
    Route::get('solar/shipment/create', 'SolarController@craeteShipment')->name('solarshipmentcreate');
    Route::post('solar/shipment', 'solarController@addShipment')->name('solarshipment');
    Route::post('generator/shipment', 'GeneratorController@addShipment')->name('shipment');
  

    Route::get('poweraction', [App\Http\Controllers\GeneratorController::class,'powerAction'])->name('poweraction');
  
   
    Route::resource('gene', 'AuditsController');
 
    Route::get('ampere/track', 'AuditsController@amperetrack');
   
    Route::get('/users/{id}/password', 'UserController@password')->name('editpassword');
    Route::post('/users/{id}/password', 'UserController@changePassword')->name('userpassword');

    Route::get('cabinetactions', 'CabinetController@actions')->name('cabinetactions');
    Route::get('bactions', 'BatteryController@actions')->name('bactions');
    Route::get('solar/actions', 'SolarController@addaction')->name('solaractions');



    Route::delete('tanks/{tank}','TankController@destroy')->name('tankdes');
  

 

    
 



});


Route::get('/p', [App\Http\Controllers\siteController::class, 'test']);



 Route::get('oi', 'sitecontroller@exportt');
 Route::post('oi', 'sitecontroller@exportt');
 Route::get('generator/export/',  'GeneratorController@export')->name('geneexport');

 Route::get('cabinets/{cabinet}/e', 'CabinetController@editnumber');
 Route::post('cabinets/s', 'CabinetController@updatenumber');

 Route::get('dismantle/{generator}/e', 'generatorController@editdismantle');
 Route::post('dismantle/s', 'generatorController@updatedismantle');
 
 Route::get('reshuffling/{generator}/e', 'generatorController@editreshuffling');
 Route::post('reshuffling/s', 'generatorController@updatereshuffling');
 Route::get('cabinetreshuffling/{cabinet}/e', 'cabinetController@editreshuffling');
 Route::post('cabinetreshuffling/s', 'cabinetController@updatereshuffling');

app/Models/Solar.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use App\Models\Battery;
use App\Models\Warehouse;
use App\Models\Site;
use App\Models\Audit;
use App\Models\Generatorpoweraction;
use OwenIt\Auditing\Auditable;




use OwenIt\Auditing\Contracts\Auditable as AuditableContract;
class Solar extends Model implements AuditableContract
{
  use \OwenIt\Auditing\Auditable;
    use HasFactory;
  protected $fillable=['po','installation_date','dismantle_date','site_id','shipment_date','controller','controller_brand','solar_project','panel_brand','panel_capacity','	number_of_panel','number_of_charger','number_of_panel'];
  
    public function battery(){
        return $this->hasMany(Battery::class, 'solar','id');
    }
    public function site(){
      return $this->belongsTo(Site::class);
    }


    public function warehouse(){
        return $this->belongsTo(Warehouse::class);
      }
   /* public function __construct(array $attributes = [])
    {        
    
        $this->created([$this, 'onCreated']);
        $this->deleted([$this, 'onDeleted']);
        
        parent::__construct($attributes);
    }*/
  /*  public function onCreated(\App\Models\Solar $solar)
    {
      if($solar->site){
        $solar->site->updatePowerSolar();
        $solar->site->save();
      }
    }*/
   
    public function generatorpoweraction(  )  
    {
        return $this->hasMany(Generatorpoweraction::class);
    }
}

resources/views/solars/create.blade.php
@extends('layouts.app')
@section('content')
@if ($errors->any())

<div class="alert alert-danger">
   <ul>
       @foreach ($errors->all() as $error)
           <li>

            {{ $error }}</li>
       @endforeach
   </ul>
</div>
@endif
<center>
    <p>Create new solar</p>
</center>
<form action="{{route('solars.store')}}" method="POST">
    @csrf

    
    <div class="raw">
<div class="column">
<div class="form-group">
                <strong>Site code:</strong>
                <input type="text" name="site_code" class="form-control" placeholder="Site code" id="site_code" required>
                <span id="error-message" style="color: red; display: none;">* the site is not available *</span>

        </div>



    <div class="form-group">
        <strong> Number of panel:</strong>
        <input type="number" name="number_of_panel" class="form-control" placeholder="Number of panel" required>

    </div>
 

    <div class="form-group">
                <strong>Po:</strong>
                
          <input type="number" name="po" class="form-control" placeholder="po" required>
        </div>
        
  <div class="form-group">
                <strong>Solar project:</strong>
                <input type="text" name="solar_project" class="form-control" placeholder="Solar project" required>


        </div>
        
        <div class="form-group">
                <strong> Installation date:</strong>
                <input type="date" name="installation_date" class="form-control" placeholder="Installation date" required>


        </div>
        <div class="form-group">
                <strong> PR:</strong>
                <input type="number" name="pr" class="form-control" placeholder="PR" required>


        </div>
    </div>

    <div class="column">
    <div class="form-group">
        <strong>Controller:</strong>
        <input type="number" name="controller" class="form-control" placeholder="Controller" required>

    </div>
    <div class="form-group">
                <strong> Panel capacity:</strong>
                <input type="number" name="panel_capacity" class="form-control" placeholder="Panel capacity" required>


        </div>
        
      

        <div class="form-group">
                <strong>Panel brand:</strong>
                <input type="text" name="panel_brand" class="form-control" placeholder="Panel brand" required>


        </div>
        <div class="form-group">
                <strong>Number of charger:</strong>
                <input type="text" name="number_of_charger" class="form-control" placeholder="Number of charger" required>


        </div>
        <div class="form-group">
                <strong>Status:</strong>
                <select type="text" name="status" class="form-control" required>

                <option value="">Select solar status</option>
<option value="used">Usesd</option>

<option value="new">New</option>
</select>
        </div>
      
        </div>



<div class="pull-right">
    <button class="button">create</button>
   </div>
    </div>

</div>


</form>
</div>
</div>
<script>

        $(document).ready(function(){

                $("#site_code").on('change', function(){
        var siteCode = $(this).val();

$.ajax({
        url: "{{ route('cheack_site') }}",
            method: 'POST',
            data: {
                _token: "{{ csrf_token() }}",
                site_code: siteCode
            },
            dataType:'json',
         
            success: function(response) {
           if(response.b){
            
           }
              if(response.a){
                $('#error-message').hide();
              }
              else{
                $('#error-message').show();
      
            document.getElementById("site_code").value="";

              }
            
    },
});

});
        });
</script>

@endsection

resources/views/solars/createwarehouse.blade.php
@extends('layouts.app')
@section('content')

@if ($errors->any())

<div class="alert alert-danger">
   <ul>
       @foreach ($errors->all() as $error)
           <li>

            {{ $error }}</li>
       @endforeach
   </ul>
</div>
@endif







<form action="{{route('solarshipment')}}" method="POST" id="myForm">
    @csrf
    <div class="raw">
<div class="column">




  <div class="form-group">
     <strong>Warehouse  name:</strong>
      <input type="text" name="warehouse_name" id="warehouse_name"class="form-control" placeholder="Warehouse" required>
      <span id="error-message" style="color: red; display: none;">* the warehouse is not available *</span>
  </div>
            

          


            <div class="form-group">
        <strong>PO:</strong>
        <input type="number" name="po" class="form-control" placeholder="po" required>

    </div>

  
    <div class="form-group">
        <strong>Shipment date:</strong>
        <input type="date" name="shipment_date" class="form-control" placeholder="Shipment date" required>

    </div>

    <div class="form-group">
        <strong>Panel brand:</strong>
        <input type="text" name="panel_brand" class="form-control" placeholder="Panel brand" required>

    </div>
    <div class="form-group">
        <strong>Number of panel:</strong>
        <input type="number" name="number_of_panel" class="form-control" placeholder="Number of panel" required>

    </div>
</div>
<div class="column">





<div class="form-group">
<strong>Controller:</strong>
    <input type="number" name="controller" class="form-control" placeholder="Controller" required>

</div>



<div class="form-group">
    <strong>Solar project :</strong>
    <input type="text" name="solar_project" class="form-control" placeholder="Solar project..." required>

</div>

<div class="form-group">
        <strong>Panel capacity:</strong>
        <input type="text" name="panel_capacity" class="form-control" placeholder="Panel capacity" required>

    </div>
    
<div class="form-group">
        <strong>Number of charger:</strong>
        <input type="number" name="number_of_charger" class="form-control" placeholder="Number of charger" required>

    </div>

</div>





<div class="pull-right">

    <button class="button" type="submit" >Add</button>
   </div>
    </div>

</div>


</form>
</div>
</div>
<script>
    $("#warehouse_name").on('change',function(){

 var warehouseName= $(this).val();
 console.log(warehouseName);
 $.ajax({
    url: "{{ route('cheack_warehouse') }}",
    method: 'POST',
            data: {
                _token: "{{ csrf_token() }}",
                warehouse_name:warehouseName
            },
            dataType:'json',
         
            success: function(response) {
        
              if(response.a){
               
                $('#error-message').hide();
              
              }
              if(response.b){
        
                $('#error-message').show();
      
            document.getElementById("warehouse_name").value="";

              }
            
    },
 });

    });
</script>

@endsection

resources/views/solars/edit.blade.php
@extends('layouts.app')
@section('content')

<form action="{{route('solars.update',$solar->id)}}" method="POST">
    @csrf
    @method('PUT')
    @if ($errors->any())


    <div class="alert alert-danger">
       <ul>
           @foreach ($errors->all() as $error)
               <li>{{ $error }}</li>
           @endforeach
       </ul>
    </div>

    @endif
<div class="raw">
    <div class="column">

        
      
   
    <div class="col-xs-12 col-sm-12 col-md-12">

  


        </div>

        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Panel capacity:</strong>
                <input type="number" name="panel_capacity"

                value="{{$solar->panel_capacity}}"
                class="form-control" required>

            </div>


        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>PO:</strong>
            <input type="number" name="po"
            value="{{$solar->po}}"
            class="form-control" required >

        </div>



        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Number of charger:</strong>
            <input type="number" name="number_of_charger"
            value="{{$solar->number_of_charger}}"
            class="form-control" required >

        </div>



        </div>
     
    </div>
<div class="column">

 
<div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Panel brand:</strong>
                <input type="text" name="panel_brand"
                value="{{$solar->panel_brand}}"
                class="form-control" placeholder="Generator capacity" required>

            </div>


        </div>
<div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Controller:</strong>
                <input type="text" name="controller"

                value="{{$solar->controller}}"
                class="form-control" placeholder="Controller" required>

            </div>


        </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Solar project:</strong>
            <input type="text" name="solar_project"
            value="{{$solar->solar_project}}"
            class="form-control" required>

        </div>
    </div>

 

</div>
<div class="pull-right">
<button class="button" type="submit" >Update</button>
</div>
</form>
</div>

          
    @endsection

resources/views/solars/import.blade.php
@extends('layouts.app')
@section('content')
 
<div class="container mt-5">
 
   
  @if(session('u'))
    <div class="alert alert-success">
        {{ session('u') }}
    </div>
  @endif
 
  <div class="card">
 
    <div class="card-header font-weight-bold">
      <h2 class="float-left">  <p>Import the solar file</p> </h2>
   
    </div>
 
    <div class="card-body">
 
        <form id="excel-csv-import-form" method="POST"  action="{{ url('import-solar') }}" accept-charset="utf-8" enctype="multipart/form-data">
 
          @csrf
                   
        

          @if (count($errors) > 0)
                <div class="row">
                    <div class="col-md-8 col-md-offset-1">
                      <div class="alert alert-danger alert-dismissible">
                          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">okay!!</button>
                          <h4><i class="icon fa fa-ban"></i> Sorry!</h4>
                          @foreach($errors->all() as $error)
                          {{ $error }} <br>
                          @endforeach      
                      </div>
                    </div>
                </div>
                @endif



            <div class="row">
 
                <div class="col-md-12">
                    <div class="form-group">
                        <input type="file" name="file" placeholder="Choose file">
                    </div>
                    @error('file')
                        <div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
                    @enderror
                </div>              
  
                <div class="col-md-12">
                    <button type="submit" class="btn btn-primary" id="submit"> Import </button>
                </div>
            </div>     
        </form>
 
    </div>
 
  </div>
 
</div>  
@endsection

resources/views/solars/index.blade.php
@extends('layouts.app')
@section('content')
@if ($message=Session::get('success'))


<div class="container">
    <div class="alert alert-primary" role="alert">
        {{$message}}
    </div>
</div>
@endif
<center>
        <h3 class="header">Solars Information</h3>

    </center>
<div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">

                        <h4>
                            <div class="pull-right">
                         
                            <a href="{{route('solars.create')}}">    <button type="button" class="btn btn-outline-success">Add new solar</button></a>
@can('admin')
                            <a href="{{route('solaractions')}}">    <button type="button" class="btn btn-outline-success">Add actions</button></a>
                            @endcan
                            @can('track')
                            <a href="{{route('solar_track')}}">    <button type="button" class="btn btn-outline-success">Track</button></a>
                            @endcan
                            <a href="{{route('solarswarehouse')}}">    <button type="button" class="btn btn-outline-success" >Warehouse</button></a>
                    </div>   

                        </h4>

                        <h6>
   
                        <div class="dropdown">
  <button class="btn btn-outline-danger" >Solar actions</button>
  <div id="myDropdown" class="dropdown-content">
    <a href="{{route('solarinstall')}}">Installation</a>
    <a href="{{route('solarre')}}">Reshuffling</a>
    <a href="{{route('solardismantle')}}">Dismantle</a>
  </div>
</div>
 
            
                        </h6>
                  
                       
                    </div>
                    <div class="card-body">

                        <table class="table table-bordered table-striped" id="example" width="100%">
                            <thead>
                                <tr>
                                
            <th style="text-align:center" class="formTableTitle" style="text-align:center" nowrap ><span class="tableheadtext" >Solar ID</span> </th>
            <th style="text-align:center" class="formTableTitle" style="text-align:center" nowrap ><span class="tableheadtext" >Site Code</span> </th>
            <th style="text-align:center" class="formTableTitle" style="text-align:center" nowrap ><span class="tableheadtext" >Panel numbers</span> </th>
            <th style="text-align:center" class="formTableTitle" style="text-align:center" nowrap ><span class="tableheadtext" >Panel brand</span> </th>
            <th style="text-align:center" class="formTableTitle" style="text-align:center" nowrap ><span class="tableheadtext" >Panel capacity</span> </th>
            <th style="text-align:center" class="formTableTitle" style="text-align:center" nowrap ><span class="tableheadtext" >Controller</span> </th>
            <th style="text-align:center" class="formTableTitle" style="text-align:center" nowrap ><span class="tableheadtext" >Battery</span> </th>
            <th style="text-align:center" class="formTableTitle" style="text-align:center" nowrap ><span class="tableheadtext" >Number of charger</span> </th>
            <th style="text-align:center" class="formTableTitle" style="text-align:center" nowrap ><span class="tableheadtext" >Status</span> </th>
            <th style="text-align:center" class="formTableTitle" style="text-align:center" nowrap ><span class="tableheadtext" >PO</span> </th>
            <th style="text-align:center" class="formTableTitle" style="text-align:center" nowrap ><span class="tableheadtext" >Solar project</span> </th>
            <th style="text-align:center" class="formTableTitle" style="text-align:center" nowrap ><span class="tableheadtext" > Installation date</span> </th>
            @can('edit')
            <th style="text-align:center" class="formTableTitle" style="text-align:center" nowrap ><span class="tableheadtext" >Edit</span> </th>
            @endcan
            @can('delete')
            <th style="text-align:center" class="formTableTitle" style="text-align:center" nowrap ><span class="tableheadtext" >Delete</span> </th>
            @endcan
         </tr>
        <tbody>
            @foreach ($solar as $v)
            <tr>
            <td style="text-align:center">{{$v->id}}</td>
            <td style="text-align:center">{{$v->site->site_code}}</td>
            <td style="text-align:center">{{$v->number_of_panel}}</td>
            <td style="text-align:center">{{$v->panel_brand}}</td>
            <td style="text-align:center">{{$v->panel_capacity}}</td>
            <td style="text-align:center">{{$v->controller}}</td>
       
            <td style="text-align:center"> @foreach ($v->Battery as $y) <li> id ({{$y->id}})  numbers ({{$y->numbers}} )</li> 
            @endforeach </td>
               <td style="text-align:center">{{$v->number_of_charger}}</td> 
               <td style="text-align:center">{{$v->status}}</td>    
            <td style="text-align:center">{{$v->po}}</td> 
            <td style="text-align:center">{{$v->solar_project}}</td> 
       
            <td style="text-align:center">{{$v->installation_date}}</td>
            @can('edit')
            
            <td style="text-align:center"><a class='fa fa-edit' style='color: #00678f' style="font-size: 19px;   color: rgb(255, 0, 0);" href="{{route('solars.edit',$v->id)}}"></a></td>
            @endcan
            @can('delete')
            <td style="text-align:center">
        
        <form action="{{route('solars.destroy',$v->id)}}" method="POST">
            @csrf
            @method('DELETE')

<button type="submit"  class='bi bi-trash'  style='color: red' style="font-size: 19px;   color: rgb(255, 0, 0);" onclick="return confirm('Are you sure you want delete the solar?')" ></button>
        </form>
        </td>
            @endcan
            @endforeach
        </table>
     

       

 
        </div>
                </div>
            </div>
        </div>
    </div>


</div>
<script>
   $(document).ready(function() {
   
            $('#example thead tr').clone(true).appendTo( '#example thead' );
            $('#example thead tr:eq(1) th').each( function (i) {

                var title = $(this).text();

                $(this).html( '<input type="text" placeholder=" Search '+title+'" />' );
              
                $( 'input', this ).on( 'keyup change', function () {
                    if ( table.column(i).search() !== this.value ) {
                        table
                         .column(i)
                            .search( this.value )
                            .draw();
                    }
                });
            });
   
            var table = $('#example').DataTable( {
                    
                orderCellsTop: true,
                fixedHeader: true,
                dom: 'Bfrtip',       
        buttons: [
           
    {
                extend: 'excel',
                exportOptions: {
                    columns: ':visible'
                }},
                {
                extend:  'csv',
                exportOptions: {
                    columns: ':visible'
                }},
                {
                extend:  'pdf', 
                exportOptions: {
                    columns: ':visible'
                }},
                {
                extend:  'copy',
                exportOptions: {
                    columns: ':visible'
                }},
                
                'colvis'
   ],
   columnDefs: [ {
            targets:[-1,-2,-3,-4,-5,-6] ,
            visible: false
        } ],
   columns: [
    {data: 'id', name: 'id'},
  {data: 'site_code', orderable: false,},
  {data: 'controller', orderable: false,},
  {data: 'panel brand', orderable: false,},
  {data: 'panel_capacity', orderable: false,},
  {data: 'Number of charger', orderable: false},
  {data: 'Last Updated by', orderable: false},
  

  {data: 'po', orderable: false},

  {data: 'solar project', orderable: false},


  {data: 'Added by', orderable: false},
  {data: 'status', orderable: false},
  {data: 'battery', orderable: false},
  @can('edit')
  {data: 'action', orderable: false},
  @endcan
  @can('delete')
  {data: 'delete', orderable: false},
@endcan
        ]
            });
        });
        
    </script>
 
 
@endsection